export const usernameMaxError = 'Username cannot exceed 100 characters';
export const passwordMaxError = 'Password cannot exceed 50 characters';
export const passwordMinError = 'Password must be at least 5 characters';
export const emailMaxError = 'Email must be at least 50 characters';
export const fullNameMaxError = 'Full Name cannot exceed 100 characters';
export const addressMaxError = 'Address cannot exceed 100 characters';
export const descriptionMaxError = 'Description cannot exceed 100 characters';
export const titleMaxError = 'Title cannot exceed 100 characters';
export const phoneNoMaxError = 'Phone No cannot exceed 100 characters';
